"""init_tables.

Revision ID: 8caed9103f2b
Revises:
Create Date: 2025-03-30 15:03:43.736913

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8caed9103f2b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("orders",
    sa.Column("id", sa.UUID(), nullable=False, comment="ID заказа"),
    sa.Column("courier_id", sa.UUID(), nullable=True, comment="ID курьера"),
    sa.Column("location_x", sa.SmallInteger(), nullable=False, comment="X координата"),
    sa.Column("location_y", sa.SmallInteger(), nullable=False, comment="X координата"),
    sa.Column("status", sa.VARCHAR(length=50), nullable=False, comment="Статус заказа"),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_table("transports",
    sa.Column("id", sa.UUID(), nullable=False, comment="ID транспорта"),
    sa.Column("name", sa.VARCHAR(length=100), nullable=False, comment="Название транспорта"),
    sa.Column("speed", sa.SmallInteger(), nullable=False, comment="Скорость транспорта"),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_transports")),
    )
    op.create_table("couriers",
    sa.Column("id", sa.UUID(), nullable=False, comment="ID курьера"),
    sa.Column("name", sa.VARCHAR(length=100), nullable=False, comment="Имя курьера"),
    sa.Column("transport_id", sa.UUID(), nullable=False, comment="ID транспорта"),
    sa.Column("location_x", sa.SmallInteger(), nullable=False, comment="X координата"),
    sa.Column("location_y", sa.SmallInteger(), nullable=False, comment="X координата"),
    sa.Column("status", sa.VARCHAR(length=50), nullable=False, comment="Статус курьера"),
    sa.ForeignKeyConstraint(["transport_id"], ["transports.id"], name=op.f("fk_couriers_transport_id_transports"), ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_couriers")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("couriers")
    op.drop_table("transports")
    op.drop_table("orders")
    # ### end Alembic commands ###
