services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/srv/www
    environment:
      - DATABASE_DSN=postgresql+psycopg://username:secret@localhost:5432/delivery
      - APP_PORT=8010
      - WATCHFILES_FORCE_POLLING=true
    network_mode: host
