services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delivery-db
    ports:
      - "5500:5432"
    volumes:
      - delivery-db:/var/lib/postgresql/data

volumes:
  delivery-db:
    driver: local
